// Error IDs
// Used for localization.

const VM_ERROR                              = 0x100000

const ERROR__VM_MEMORY_CATEGORY             = 0x10000 | VM_ERROR
export const VM_MEMORY_STRUCTURE_CORRUPT    = 1 | ERROR__VM_MEMORY_CATEGORY
export const VM_MEMORY_TYPE_CONFUSION       = 2 | ERROR__VM_MEMORY_CATEGORY

const ERROR__VM_EXECUTION                   = 0x20000 | VM_ERROR
export const VM_INSTRUCTION_ORDER_VIOLATION = 1 | ERROR__VM_EXECUTION

const ERROR__VM_BUG                         = 0xf0000 | VM_ERROR
export const VM_BUG_UNKNOWN_PRIMARY_TYPE    = 1 | ERROR__VM_BUG
export const VM_BUG_NON_EVALUATED_VALUE     = 2 | ERROR__VM_BUG


const USER_ERROR                            = 0x200000

const ERROR__USER_RUNTIME                   = 0x10000 | USER_ERROR
export const ERROR__USER__MODULE_NOT_FOUND  = 1 | ERROR__USER_RUNTIME
export const ERROR__USER__CONST_NOT_FOUND   = 2 | ERROR__USER_RUNTIME
export const ERROR__USER__TYPE_MISMATCH     = 3 | ERROR__USER_RUNTIME
export const ERROR__USER__UNKOWN_TYPE       = 4 | ERROR__USER_RUNTIME


const IMPL_ERROR                            = 0x300000

const ERROR__IMPL_RUNTIME                   = 0x10000 | IMPL_ERROR
export const ERROR__IMPL_RETURN_VALUE_TYPE  = 1 | ERROR__IMPL_RUNTIME

const ERROR__IMPL_SETUP                               = 0x20000 | IMPL_ERROR
export const ERROR__IMPL_DUPLICATE_OPCODES            = 1 | ERROR__IMPL_SETUP
export const ERROR__IMPL_DUPLICATE_GENERIC_BINDING    = 2 | ERROR__IMPL_SETUP
export const ERROR__IMPL_GENERIC_BINDING_INDEX        = 3 | ERROR__IMPL_SETUP
export const ERROR__IMPL_GENERIC_BINDING_DEEP         = 4 | ERROR__IMPL_SETUP
export const ERROR__IMPL_GENERIC_BINDING_STATE        = 5 | ERROR__IMPL_SETUP
export const ERROR__IMPL_GENERIC_BINDING_FROM_TYPE    = 6 | ERROR__IMPL_SETUP
export const ERROR__IMPL_GENERIC_BINDING_KEYED_TYPE   = 7 | ERROR__IMPL_SETUP
export const ERROR__IMPL_ARGUMENT_RUNTIME_TYPE        = 8 | ERROR__IMPL_SETUP
export const ERROR__IMPL_ARGUMENT_EVAL_SHALLOW_SIMPLE = 9 | ERROR__IMPL_SETUP
export const ERROR__IMPL_UNBOUND_GENERIC              = 10 | ERROR__IMPL_SETUP
export const ERROR__IMPL_ARGUMENT_REQUIRES_STRUCT_BINDING = 11 | ERROR__IMPL_SETUP
export const ERROR__IMPL_DUPLICATE_TYPE               = 12 | ERROR__IMPL_SETUP

const ERROR__IMPL_SCRIPT                             = 0x30000 | IMPL_ERROR
export const ERROR__IMPL_MISSING_NATIVE_TYPE         = 1 | ERROR__IMPL_SCRIPT
export const ERROR__IMPL_MISSING_DECLARED_TYPE       = 2 | ERROR__IMPL_SCRIPT
export const ERROR__IMPL_CONFLICTING_TYPES           = 3 | ERROR__IMPL_SCRIPT
export const ERROR__IMPL_DUPLICATE_MODULE_NAMES      = 4 | ERROR__IMPL_SCRIPT
export const ERROR__IMPL_CONSTANT_GENERIC_TYPE       = 5 | ERROR__IMPL_SCRIPT
export const ERROR__IMPL_UNKNOWN_TYPE_CATEGORY       = 6 | ERROR__IMPL_SCRIPT
export const ERROR__IMPL_TYPE_VALUE_MISMATCH         = 7 | ERROR__IMPL_SCRIPT
export const ERROR__IMPL_INSUFFICIENT_CALL_CELLS     = 8 | ERROR__IMPL_SCRIPT
export const ERROR__IMPL_NO_SUCH_CONSTANT            = 9 | ERROR__IMPL_SCRIPT
export const ERROR__IMPL_INVALID_RETURN_CELL         = 11 | ERROR__IMPL_SCRIPT

const ERROR__IMPL_INVOKE                             = 0x40000 | IMPL_ERROR
export const ERROR__IMPL_NOT_CALLABLE                = 1 | ERROR__IMPL_INVOKE
