// Validation IDs
// Used for localization.

const VM_VALIDATION                           = 0x800000

const VALIDATION__OPCODE                      = 0x10000 | VM_VALIDATION
export const VALIDATION_OPCODE_ARGUMENT_COUNT = 1 | VALIDATION__OPCODE
export const VALIDATION_OPCODE_ARGUMENT_TYPE  = 2 | VALIDATION__OPCODE
export const VALIDATION_OPCODE_ARGUMENT_REF   = 3 | VALIDATION__OPCODE
export const VALIDATION_OPCODE_ARGUMENT_VALUE = 4 | VALIDATION__OPCODE

const VALIDATION__USER_SCRIPT                     = 0x20000 | VM_VALIDATION
export const VALIDATION_USER_SCRIPT_BAD_FORMAT    = 1 | VALIDATION__USER_SCRIPT
export const VALIDATION_USER_SCRIPT_BAD_STRUCTURE = 2 | VALIDATION__USER_SCRIPT
